config/routes.rb
Rails.application.routes.draw do
  get 'android/one'

  get 'android/two'

  get 'android/three'

  get 'android/four'

  get 'android/five'

  get 'android/six'

  get 'android/seven'

  get 'android/eight'

  get 'android/nine'

  get 'android/ten'

  get 'programming/one'

  get 'programming/two'

  get 'programming/three'

  get 'programming/four'

  get 'programming/five'

  get 'programming/six'

  get 'programming/seven'

  get 'programming/eight'

  get 'programming/nine'

  get 'programming/ten'

  get 'projects/thissite'

  get 'projects/network'

  get 'projects/clock'

  get 'projects/news'

  get 'lessons/programming'

  get 'lessons/html'

  get 'lessons/linux'

  get 'lessons/home'

  get 'lessons/android'

  get 'lessons/html_css'

  get 'lessons/javascript'

  get 'lessons/ruby_rails'

  devise_for :users
  get 'pages/index'

  get 'pages/about'

  get 'pages/portfolio'

  get 'pages/lessons'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "pages#index"

  resources :pages
  resources "contacts", only: [:new, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "pastrana.steven.az@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable

         
end

app/controllers/android_controller.rb
class AndroidController < ApplicationController
  def one
  end

  def two
  end

  def three
  end

  def four
  end

  def five
  end

  def six
  end

  def seven
  end

  def eight
  end

  def nine
  end

  def ten
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
      flash.now[:notice] = 'Thank you for your message!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def programming
  end

  def html
  end

  def linux
  end

  def android
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def portfolio
  end

  def lessons
  end

  def clock
  end

  def network
  end

end

app/controllers/programming_controller.rb
class ProgrammingController < ApplicationController
  def one
  end

  def two
  end

  def three
  end

  def four
  end

  def five
  end

  def six
  end

  def seven
  end

  def eight
  end

  def nine
  end

  def ten
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def thissite
  end

  def network
  end

  def clock
  end

  def news
  end
end

app/helpers/android_helper.rb
module AndroidHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/programming_helper.rb
module ProgrammingHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/android/eight.html.erb
<h1>Android#eight</h1>
<p>Find me in app/views/android/eight.html.erb</p>

app/views/android/five.html.erb
<h1>Android#five</h1>
<p>Find me in app/views/android/five.html.erb</p>

app/views/android/four.html.erb
<h1>Android#four</h1>
<p>Find me in app/views/android/four.html.erb</p>

app/views/android/nine.html.erb
<h1>Android#nine</h1>
<p>Find me in app/views/android/nine.html.erb</p>

app/views/android/one.html.erb
<h1>Android#one</h1>
<p>Find me in app/views/android/one.html.erb</p>

app/views/android/seven.html.erb
<h1>Android#seven</h1>
<p>Find me in app/views/android/seven.html.erb</p>

app/views/android/six.html.erb
<h1>Android#six</h1>
<p>Find me in app/views/android/six.html.erb</p>

app/views/android/ten.html.erb
<h1>Android#ten</h1>
<p>Find me in app/views/android/ten.html.erb</p>

app/views/android/three.html.erb
<h1>Android#three</h1>
<p>Find me in app/views/android/three.html.erb</p>

app/views/android/two.html.erb
<h1>Android#two</h1>
<p>Find me in app/views/android/two.html.erb</p>

app/views/contacts/_new.html.erb
<%= form_for Contact.new do |f| %>
<div class="form-group">
  <%= f.label :name %><br>
  <%= f.text_field :name, :class => "form-control" %><br />
</div>
<div class="form-group">
  <%= f.label :email %><br>
  <%= f.text_field :email, :class => "form-control" %><br />
</div>
<div class="form-group">
  <%= f.label :message %><br>
  <%= f.text_area :message, size: "50x10", :class => "form-control" %>
</div>
<div class="hidden">
  <%= f.label :nickname %><br>
  <%= f.text_field :nickname, :hint => 'leave this area blank' %>
</div>
  <br>
<div class="actions">
  <%= f.submit "Send", class: 'btn btn-primary', id: 'submit-button' %>
</div>

<% end %>

app/views/contacts/create.html.erb
<div class="container-fluid" id="response">
  <h1>Thank you for reaching out</h1>
  <p>I will get back to you soon<p>
  <br>
  <%= link_to "Back to Home", pages_index_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Android theme -->
    <meta name="theme-color" content="#003E40">
    <!-- Windows Phone -->
    <meta name="msapplication-navbutton-color" content="#003E40">
    <!-- iOS Safari -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="#003E40">

    <!--///////////////////////////////////////////
    /////_________The Scripts_________________/////
    ////////////////////////////////////////////-->
    <script src="https://use.fontawesome.com/0b63b9ae91.js"></script>
    <script src="jquery.slides.min.js"></script>
    <!-------------------------------------------->

    <title>Stevenantonio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<%= render partial: "shared/sidebar" %>
    <!--
    <p class="notice"><%= notice %></p>

    <p class="alert"><%= alert %></p>
    -->
<div class="container" id="alert">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>
</div>

    <%= yield %>

<%= render partial: "shared/footer" %>


  </body>
</html>

app/views/lessons/android.html.erb
<%= render partial: "shared/comingsoon" %>

app/views/lessons/home.html.erb
<h1>Lessons#home</h1>
<p>Find me in app/views/lessons/home.html.erb</p>

app/views/lessons/html.html.erb
<%= render partial: "shared/comingsoon" %>

app/views/lessons/html_css.html.erb
<h1>Lessons#html_css</h1>
<p>Find me in app/views/lessons/html_css.html.erb</p>

app/views/lessons/javascript.html.erb
<h1>Lessons#javascript</h1>
<p>Find me in app/views/lessons/javascript.html.erb</p>

app/views/lessons/linux.html.erb
<%= render partial: "shared/comingsoon" %>

app/views/lessons/programming.html.erb
<%= render partial: "shared/comingsoon" %>

app/views/lessons/ruby_rails.html.erb
<h1>Lessons#ruby_rails</h1>
<p>Find me in app/views/lessons/ruby_rails.html.erb</p>

app/views/pages/about.html.erb
This is the page about this particular site!

app/views/pages/index.html.erb
<!-- This is the jumbotron area -->
<div class="container-fluid" id="jumbo">
  <div class="container" id="title-content">
    <%= image_tag "mecircshadow.png", :id => "title-content-image" %>
    <div class="container-fluid"><h1 id="title-content-text">stevenanton.io</h1></div>
  </div>
</div>
<!-- End of jumbotron area -->


<div class="box" id="intro-content">

  <div class="container-fluid" id="contact-form">

    <div class="hideme center">
      <%= image_tag "lovecode.jpg", :class => "codepic" %>
    </div>

      <p class="hideme">Hi there. I’m Steven. I’m a software geek! I made this site as a labor of love. It’s my own home away from…… the office. It’s my project to help democratize knowledge & the power to build things.</p>
      <div class="hideme center">
        <%= image_tag "phonecode.jpg", :class => "codepic" %>
      </div>

      <p class="hideme">Software is a beautiful thing. It’s freeing; yet structured. It has empowered the dramatic growth of productivity. It’s pushed progress in an unparalleled upward trend</p>
      <div class="hideme center">
        <%= image_tag "earth.jpg", :class => "codepic" %>
      </div>


      <p class="hideme">I hope, with this site, to do my small part to democratize knowledge & the power to build things</p>
      <div class="hideme center">
        <%= image_tag "stevenantonio_logo_large.jpg", :class => "codepic" %>
      </div>

      <p class="hideme">Well….. I’m not much of a writer, so to fill in some space. Here are some pictures of my cats.</p>
      <br>



    <!--
    <div class="hideme">
    <%= render partial: "shared/about" %>
    </div>
    -->





    <hr>
    <div class="hideme">
    <%= render partial: "shared/slideshow" %>
    </div>
    <hr class="hideme">
    <br>
    <h2 class="hideme">Interested in collaborating?</h2>
    <br>
    <p class="hideme">Send me a message, and let's make something.</p>
    <br>
    <div class="hideme">
    <%= render partial: "contacts/new" %>
    </div>
    <br>
  </div>

</div>

app/views/pages/lessons.html.erb
  <div class="jumbotron">
    <div class="container">
    <% if user_signed_in? %>
    <%= render 'lessons/home' %>
    <% else %>
      <h1>Welcome!</h1>
      <p>Register to get started.</p>
      <p>
        <%= link_to 'Register', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
      </p>
    <% end %>
    </div>
  </div>

app/views/pages/portfolio.html.erb
<h1>Pages#portfolio</h1>
<p>Find me in app/views/pages/portfolio.html.erb</p>

app/views/programming/eight.html.erb
<h1>Programming#eight</h1>
<p>Find me in app/views/programming/eight.html.erb</p>

app/views/programming/five.html.erb
<h1>Programming#five</h1>
<p>Find me in app/views/programming/five.html.erb</p>

app/views/programming/four.html.erb
<h1>Programming#four</h1>
<p>Find me in app/views/programming/four.html.erb</p>

app/views/programming/nine.html.erb
<h1>Programming#nine</h1>
<p>Find me in app/views/programming/nine.html.erb</p>

app/views/programming/seven.html.erb
<h1>Programming#seven</h1>
<p>Find me in app/views/programming/seven.html.erb</p>

app/views/programming/six.html.erb
<h1>Programming#six</h1>
<p>Find me in app/views/programming/six.html.erb</p>

app/views/programming/ten.html.erb
<h1>Programming#ten</h1>
<p>Find me in app/views/programming/ten.html.erb</p>

app/views/programming/three.html.erb
<h1>Programming#three</h1>
<p>Find me in app/views/programming/three.html.erb</p>

app/views/programming/two.html.erb
<h1>Programming#two</h1>
<p>Find me in app/views/programming/two.html.erb</p>

app/views/projects/clock.html.erb
<%= render partial: "shared/comingsoon" %>

app/views/projects/network.html.erb
<%= render partial: "shared/comingsoon" %>

app/views/projects/news.html.erb
<%= render partial: "shared/comingsoon" %>

app/views/projects/thissite.html.erb
<%= render partial: "shared/comingsoon" %>

app/views/shared/_about.html.erb
  <p>Hi there. I’m Steven. I’m a software geek! I made this site as a labor of love. It’s my own home away from…… the office. It’s my project to help democratize knowledge & the power to build things.

  </p>
  <br>
  <p>Software is a beautiful thing. It’s freeing; yet structured. It has empowered the dramatic growth of productivity. It’s pushed progress in an unparalleled upward trend

  </p>
  <br>
  <p>I hope this site can help change the world

  </p>
  <br>
  <p>Well….. I’m not much of a writer, so to fill in some space. Here are some pictures of my cats.

  </p>
  <br>

app/views/shared/_comingsoon.html.erb
<div class="under-construction container-fluid">
  <p class="center">Sorry, not much here yet</p>
  <p class="center">Be sure to check back soon</p>
  <%=image_tag "comingsoon.png", :id => "comingsoon-image" %>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
      <div class="container">
        <div class=row>
          <div class="col-xs-6">
            <p class="text-muted" id= footer-text>2016 | stevenanton.io</p>
          </div>
          <div class="col-xs-6" id="social-icons">
          <a href= "https://twitter.com/steven_az"><i class="fa fa-twitter" aria-hidden="true" id="twit-icon"></i></a>
          <a href= "https://github.com/pastranastevenaz"><i class="fa fa-github" aria-hidden="true" id="git-icon"></i></a>

          </div>
        </div>
      </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("stevenantonio_logo.png", alt: "logo", :id=>"logo"), '/', class: 'navbar-brand' %>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active" id="home-link"><a href="#"><strong>stevenanton.io</strong> <span class="sr-only">(current)</span></a></li>
        <li id="about-link"><%= link_to "About", pages_about_path %></li>
        <!--
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
        -->
      </ul>
      <!--
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      -->
      <ul class="nav navbar-nav navbar-right">
        
        <li id="dropdown-link" class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li id="lessons-link"><%= link_to "Lessons", pages_lessons_path %></li>
            <li id="portfolio-link"><%= link_to "Portfolio", pages_portfolio_path %></li>
            <!--
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            -->
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_new.html.erb
<%= form_for @contact do |f| %>
  <%= f.input :name, :required => true, :class => 'form-control'  %>
  <%= f.input :email, :required => true, :class => 'form-control'  %>
  <%= f.input :message, as: :text, :required => false, :input_html => {:rows => 10}, :class => 'form-control' %>
  <div class="hidden">
    <%= f.input :nickname, :hint => 'leave this blank' %>
  </div>
  <%= f.button :submit, :class => 'btn btn-primary' %>
<% end %>

app/views/shared/_sidebar.html.erb
<nav class="nav-side" >
	<span class="nav-title"><%= link_to "Home", pages_index_path, :id => 'nav-home' %></span>
	<br>
	<br>
	<span class="nav-title">Lessons</span>
  <hr>
  <div class="nav-link"><%= link_to "Programming", programming_one_path, :class => 'nav-content' %></div>
  <div class="nav-link"><%= link_to "HTML & CSS", lessons_html_path, :class => 'nav-content' %></div>
  <div class="nav-link"><%= link_to "Linux", lessons_linux_path, :class => 'nav-content' %></div>
	<div class="nav-link"><%= link_to "Android", lessons_android_path, :class => 'nav-content' %></div>

	<span class="nav-title">Portfolio</span>
  <hr>
	<div class="nav-link"><%= link_to "This Site", projects_thissite_path, :class => 'nav-content' %></div>
	<div class="nav-link"><%= link_to "Network Widget", projects_network_path, :class => 'nav-content' %></div>
	<div class="nav-link"><%= link_to "Android Clock", projects_clock_path, :class => 'nav-content' %></div>
	<div class="nav-link"><%= link_to "News Aggregator", projects_news_path, :class => 'nav-content' %></div>

	<br>
	<a href="#" class="nav-toggle">
    <%= image_tag "arrowwhite.png", :id => 'nav-arrow' %>
  </a>
</nav>


</div>

app/views/shared/_slideshow.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
    <li data-target="#carousel-example-generic" data-slide-to="4"></li>
    <li data-target="#carousel-example-generic" data-slide-to="5"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag "cats/a_pambele1.jpg" %>
      <div class="carousel-caption">
      	<h3>Pambele</h3>
      </div>
    </div>
    <div class="item">
      <%= image_tag "cats/a_hil1.jpg" %>
      <div class="carousel-caption">
      	<h3>Hillary</h3>
      </div>
    </div>
    <div class="item">
      <%= image_tag "cats/a_reni1.jpg" %>
      <div class="carousel-caption">
      	<h3>Renate</h3>
      </div>
    </div>
    <!--
    <div class="item">
      <%= image_tag "cats/a_pambele2.jpg" %>
      <div class="carousel-caption">
      	<h3>Pambele</h3>
      </div>
    </div>
  -->
    <div class="item">
      <%= image_tag "cats/a_hil2.jpg" %>
      <div class="carousel-caption">
      	<h3>Hillary</h3>
      </div>
    </div>
    <div class="item">
      <%= image_tag "cats/a_reni2.jpg" %>
      <div class="carousel-caption">
      	<h3>Renate</h3>
      </div>
    </div>
    <div class="item">
      <%= image_tag "cats/a_pambele3.jpg" %>
      <div class="carousel-caption">
      	<h3>Pambele</h3>
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="icon-prev"></span>
    <!--<span class="glyphicon slideshow-icon" id="left-arrow"><</span>-->
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="icon-next"></span>
    <!--<span class="glyphicon slideshow-icon">></span>-->
  </a>
</div> <!-- Carousel -->